server:
  port: 8077
  servlet:
    context-path: /rotaslz

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/rotaslz
    username: root
    password: catarina
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        default_schema: rotaslz

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: Rotas SLZ
    version: 1.0.0
